### ISSUE TITLE
Please make lib.index.js human readable

### ISSUE THREAD

**Issue by me-kell** [Vin-it/react-sort-list#19]
Is there a reason why  [lib/index.js](https://github.com/Vin-it/react-sort-list/blob/16c321e0362864c0fd97d91b1588d60b24bd4b00/lib/index.js) is minified?

Is this file open source? What is the license? The first line reads `For license information please see index.js.LICENSE.txt`. But I cannot find a `index.js.LICENSE.txt`  file

Please make this file `human readable`

**Comment by Vin-it** [comment]
Hi @me-kell, sorry for not getting back to you earlier. 

To answer your question, I built this project because I couldn't find something similar BUT when I did I was a complete beginner. So at the time, I didn't really understand the "build" process to publish to npm so I kept it all in this repo. 

`lib/index.js` is simply the bundled (by webpack) version of `src`  

Regarding the license, I published this with [MIT License](https://opensource.org/licenses/MIT). You can find that here on the repository - https://github.com/Vin-it/react-sort-list/blob/master/LICENSE

**Comment by me-kell** [comment]
@Vin-it thanks for clarifying it!
